name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # runs once a day at midnight UTC
  workflow_dispatch:

# IMPORTANT: allow pushing to the output branch
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake files
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ymcmb0  # <-- your username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output       # this branch will be created if missing
          build_dir: dist             # this is where snk wrote the files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
